version: '3.8'

services:
  # Automatic1111 Stable Diffusion WebUI
  automatic1111:
    image: automatic1111/stable-diffusion-webui:latest
    container_name: ai-q-automatic1111
    environment:
      - COMMANDLINE_ARGS=--api --listen --port 7860 --enable-insecure-extension-access
      - REQS_FILE=requirements.txt
    volumes:
      - automatic1111_models:/app/models
      - automatic1111_outputs:/app/outputs
      - automatic1111_extensions:/app/extensions
    ports:
      - "${AUTOMATIC1111_PORT:-7860}:7860"
    networks:
      - ai-q-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:7860/sdapi/v1/samplers"]
      interval: 30s
      timeout: 10s
      retries: 3
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]

  # ComfyUI Node-Based Workflow
  comfyui:
    image: comfyanonymous/comfyui:latest
    container_name: ai-q-comfyui
    environment:
      - COMFYUI_PORT=8188
    volumes:
      - comfyui_models:/app/models
      - comfyui_outputs:/app/output
      - comfyui_custom_nodes:/app/custom_nodes
    ports:
      - "${COMFYUI_PORT:-8188}:8188"
    networks:
      - ai-q-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8188/system_stats"]
      interval: 30s
      timeout: 10s
      retries: 3
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]

  # n8n Workflow Automation
  n8n:
    image: n8nio/n8n:latest
    container_name: ai-q-n8n
    environment:
      - N8N_HOST=${N8N_HOST:-localhost}
      - N8N_PORT=${N8N_PORT:-5678}
      - N8N_PROTOCOL=${N8N_PROTOCOL:-http}
      - N8N_USER_MANAGEMENT_DISABLED=${N8N_USER_MANAGEMENT_DISABLED:-false}
      - N8N_BASIC_AUTH_ACTIVE=${N8N_BASIC_AUTH_ACTIVE:-false}
      - N8N_BASIC_AUTH_USER=${N8N_BASIC_AUTH_USER:-admin}
      - N8N_BASIC_AUTH_PASSWORD=${N8N_BASIC_AUTH_PASSWORD:-admin}
      - WEBHOOK_URL=${N8N_WEBHOOK_URL:-http://localhost:5678/}
      - GENERIC_TIMEZONE=${N8N_TIMEZONE:-UTC}
      - N8N_ENCRYPTION_KEY=${N8N_ENCRYPTION_KEY:-your-encryption-key}
    volumes:
      - n8n_data:/home/node/.n8n
    ports:
      - "${N8N_PORT:-5678}:5678"
    networks:
      - ai-q-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5678/healthz"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Penpot Design and Prototyping
  penpot:
    image: penpot/penpot:latest
    container_name: ai-q-penpot
    environment:
      - PENPOT_DATABASE_URI=${PENPOT_DATABASE_URI:-postgresql://penpot:penpot@postgres:5432/penpot}
      - PENPOT_REDIS_URI=${PENPOT_REDIS_URI:-redis://redis:6379/0}
      - PENPOT_SECRET_KEY=${PENPOT_SECRET_KEY:-your-secret-key}
      - PENPOT_PUBLIC_URI=${PENPOT_PUBLIC_URI:-http://localhost:9001}
    volumes:
      - penpot_data:/app/data
    ports:
      - "${PENPOT_PORT:-9001}:80"
    networks:
      - ai-q-network
    depends_on:
      - postgres
      - redis
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  automatic1111_models:
  automatic1111_outputs:
  automatic1111_extensions:
  comfyui_models:
  comfyui_outputs:
  comfyui_custom_nodes:
  n8n_data:
  penpot_data:

networks:
  ai-q-network:
    external: true 