version: '3.8'

services:
  # Gitea Git Server
  gitea:
    image: ${KOS_GITEA_IMAGE}:${KOS_GITEA_VERSION}
    container_name: ${KOS_GITEA_CONTAINER_NAME}
    restart: unless-stopped
    environment:
      - USER_UID=${KOS_GITEA_USER_UID}
      - USER_GID=${KOS_GITEA_USER_GID}
    ports:
      - "${KOS_GITEA_EXTERNAL_PORT}:${KOS_GITEA_INTERNAL_PORT}"
      - "${KOS_GITEA_SSH_EXTERNAL_PORT}:${KOS_GITEA_SSH_INTERNAL_PORT}"
    volumes:
      - ${KOS_GITEA_DATA_VOLUME}:/data
      - ${KOS_GITEA_CONFIG_VOLUME}:/data/gitea/conf/app.ini
    networks:
      - ${KOS_CONTAINER_NETWORK}
    healthcheck:
      test: ["CMD", "curl", "-f", "http://${KOS_GITEA_HOST}:${KOS_GITEA_INTERNAL_PORT}"]
      interval: ${KOS_HEALTH_CHECK_INTERVAL}
      timeout: ${KOS_HEALTH_CHECK_TIMEOUT}
      retries: ${KOS_HEALTH_CHECK_RETRIES}

  # NextCloud File Storage
  nextcloud:
    image: ${KOS_NEXTCLOUD_IMAGE}:${KOS_NEXTCLOUD_VERSION}
    container_name: ${KOS_NEXTCLOUD_CONTAINER_NAME}
    restart: unless-stopped
    environment:
      - NEXTCLOUD_ADMIN_USER=${KOS_NEXTCLOUD_ADMIN_USER}
      - NEXTCLOUD_ADMIN_PASSWORD=${KOS_NEXTCLOUD_ADMIN_PASSWORD}
    ports:
      - "${KOS_NEXTCLOUD_EXTERNAL_PORT}:${KOS_NEXTCLOUD_INTERNAL_PORT}"
    volumes:
      - ${KOS_NEXTCLOUD_DATA_VOLUME}:/var/www/html
      - ${KOS_NEXTCLOUD_CONFIG_VOLUME}:/var/www/html/config/config.php
    networks:
      - ${KOS_CONTAINER_NETWORK}
    healthcheck:
      test: ["CMD", "curl", "-f", "http://${KOS_NEXTCLOUD_HOST}/status.php"]
      interval: ${KOS_HEALTH_CHECK_INTERVAL}
      timeout: ${KOS_HEALTH_CHECK_TIMEOUT}
      retries: ${KOS_HEALTH_CHECK_RETRIES}

  # Admin Panel
  admin-panel:
    build:
      context: ${KOS_ADMIN_PANEL_BUILD_CONTEXT}
      dockerfile: ${KOS_ADMIN_PANEL_DOCKERFILE}
    container_name: ${KOS_ADMIN_PANEL_CONTAINER_NAME}
    restart: unless-stopped
    ports:
      - "${KOS_ADMIN_PANEL_EXTERNAL_PORT}:${KOS_ADMIN_PANEL_INTERNAL_PORT}"
    networks:
      - ${KOS_CONTAINER_NETWORK}
    healthcheck:
      test: ["CMD", "curl", "-f", "http://${KOS_ADMIN_PANEL_HOST}/health"]
      interval: ${KOS_HEALTH_CHECK_INTERVAL}
      timeout: ${KOS_HEALTH_CHECK_TIMEOUT}
      retries: ${KOS_HEALTH_CHECK_RETRIES}

  # Local Docker Registry
  registry:
    image: ${KOS_REGISTRY_IMAGE}:${KOS_REGISTRY_VERSION}
    container_name: ${KOS_REGISTRY_CONTAINER_NAME}
    restart: unless-stopped
    ports:
      - "${KOS_REGISTRY_EXTERNAL_PORT}:${KOS_REGISTRY_INTERNAL_PORT}"
    volumes:
      - ${KOS_REGISTRY_VOLUME}:/var/lib/registry
    networks:
      - ${KOS_CONTAINER_NETWORK}
    healthcheck:
      test: ["CMD", "curl", "-f", "http://${KOS_REGISTRY_HOST}:${KOS_REGISTRY_INTERNAL_PORT}/v2/"]
      interval: ${KOS_HEALTH_CHECK_INTERVAL}
      timeout: ${KOS_HEALTH_CHECK_TIMEOUT}
      retries: ${KOS_HEALTH_CHECK_RETRIES}

volumes:
  kos-gitea-data:
  kos-nextcloud-data:
  kos-registry-data:

networks:
  kos-network:
    driver: bridge
    ipam:
      config:
        - subnet: ${KOS_NETWORK_SUBNET} 
